name: Update Docker

on:
  push:
    branches:
      - 'main'

jobs:
  update-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./sources
          file: ./sources/Dockerfile
          push: true
          tags: abirmarghni/cloud-project:1.0.${{ github.run_number }}
